name: CI-PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}  
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - run: |
          echo "Checking for new migrations..."
          git fetch origin develop
          if git diff --name-only origin/develop HEAD | grep -q "supabase/migrations"; then
            echo "New migrations detected. Resetting the database..."
            echo y | supabase db reset --linked
          else
            echo "No new migrations detected."
          fi
